### ISSUE TITLE
normal logic 

### ISSUE THREAD

**Issue by rainbowkinggleeock** [jjjj12212/Archipelago-BanjoTooie#79]
so im in ggm and with bk moves random all and normal logic its saying i can get the notes on the green hill but i dont know what the trick i need to do is to get up without talon trot was wondering if you knew

**Comment by jjjj12212** [comment]
Hi rainbowkinggleeock,

This isn't the best place to post logic issues. Logic issues is better posted at the Archipelago Discord -> Future-game-design -> Banjo-Tooie where more people can assist you with logic stuff sooner.

You mean the green pile? You can use the Speed Shoes to access them right now as you are in Talon Trot mode while wearing the shoes.

Again, any further logic questions, head to the discord.
jjjj12212

**Comment by rainbowkinggleeock** [comment]
ah okay thanks and ill make sure to post any more questions in the discord also yeah i actually forgot the shoes were there even though i had used them a couple days later lol
